# Generated by Django 5.2.17 on 2026-08-29 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_onboarding_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['full_name', 'email'], 'verbose_name': 'pessoa', 'verbose_name_plural': 'pessoas'},
        ),
    ]
