# Generated by Django 5.2.17 on 2026-08-29 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistantmessage',
            options={'ordering': ['created_at'], 'verbose_name': 'mensagem do assistente', 'verbose_name_plural': 'mensagens do assistente'},
        ),
        migrations.AlterModelOptions(
            name='auditevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'evento de auditoria', 'verbose_name_plural': 'eventos de auditoria'},
        ),
    ]
