# Generated by Django 5.2.17 on 2026-08-29 00:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('internal', 'Interno'), ('mercado_pago', 'Mercado Pago')], max_length=24)),
                ('event_id', models.CharField(max_length=180)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('received', 'Recebido'), ('processed', 'Processado'), ('ignored', 'Ignorado'), ('failed', 'Falhou')], default='received', max_length=12)),
                ('error_message', models.CharField(blank=True, max_length=220)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='unique_payment_webhook_event')],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.CharField(max_length=220, verbose_name='descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço')),
                ('billing_period', models.CharField(choices=[('monthly', 'Mensal'), ('yearly', 'Anual')], default='monthly', max_length=12, verbose_name='periodicidade')),
                ('features', models.JSONField(default=list, verbose_name='recursos')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='recomendado')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('mercado_pago_plan_id', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['sort_order', 'price', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='plan_price_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('internal', 'Interno'), ('mercado_pago', 'Mercado Pago')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Aguardando pagamento'), ('active', 'Ativa'), ('paused', 'Pausada'), ('past_due', 'Pagamento pendente'), ('cancelled', 'Cancelada'), ('expired', 'Expirada'), ('failed', 'Falhou')], default='pending', max_length=16)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=120, null=True)),
                ('checkout_url', models.URLField(blank=True, max_length=500)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_2a19e8_idx'), models.Index(fields=['provider', 'provider_subscription_id'], name='subscriptio_provide_686470_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider_subscription_id__isnull', False)), fields=('provider', 'provider_subscription_id'), name='unique_provider_subscription'), models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'active', 'past_due'])), fields=('user',), name='one_open_subscription_per_user')],
            },
        ),
    ]
