# Generated by Django 5.2.17 on 2026-08-29 00:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_seed_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='one_open_subscription_per_user',
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'active', 'paused', 'past_due'])), fields=('user',), name='one_open_subscription_per_user'),
        ),
    ]
