# Generated by Django 5.2.17 on 2026-08-29 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_remove_subscription_one_open_subscription_per_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentwebhookevent',
            options={'ordering': ['-received_at'], 'verbose_name': 'evento de pagamento', 'verbose_name_plural': 'eventos de pagamento'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['sort_order', 'price', 'name'], 'verbose_name': 'plano', 'verbose_name_plural': 'planos'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'assinatura', 'verbose_name_plural': 'assinaturas'},
        ),
    ]
