# Generated by Django 5.2.17 on 2026-08-28 22:53

import apps.banking.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.CharField(default='0001', max_length=4)),
                ('number', models.CharField(default=apps.banking.models.generate_account_number, max_length=8, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=19)),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('blocked', 'Bloqueada'), ('closed', 'Encerrada')], default='active', max_length=16)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='financial_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('credit', 'Crédito'), ('debit', 'Débito')], max_length=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=19)),
                ('description', models.CharField(max_length=180)),
                ('reference', models.CharField(max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='banking.financialaccount')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_name', models.CharField(max_length=180)),
                ('pix_key', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Aguardando confirmação'), ('completed', 'Concluída'), ('cancelled', 'Cancelada'), ('failed', 'Falhou')], default='pending', max_length=16)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('failure_reason', models.CharField(blank=True, max_length=180)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='banking.financialaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['status', 'created_at'], name='banking_fin_status_18ea1c_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', '-occurred_at'], name='banking_led_account_c7e81f_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.UniqueConstraint(fields=('account', 'reference'), name='unique_ledger_reference'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['account', '-created_at'], name='banking_tra_account_264dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['status', 'created_at'], name='banking_tra_status_45ac53_idx'),
        ),
    ]
