# Generated by Django 5.2.17 on 2026-08-28 22:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_financialaccount_account_balance_nonnegative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('requested', 'Solicitado'), ('in_review', 'Em análise'), ('approved', 'Aprovado'), ('issued', 'Emitido'), ('blocked', 'Bloqueado'), ('cancelled', 'Cancelado')], default='requested', max_length=16)),
                ('last_four', models.CharField(blank=True, max_length=4)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_card', to='banking.financialaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
