# Generated by Django 5.2.17 on 2026-08-29 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_paymentcard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialaccount',
            options={'verbose_name': 'conta demonstrativa', 'verbose_name_plural': 'contas demonstrativas'},
        ),
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'ordering': ['-occurred_at', '-id'], 'verbose_name': 'lançamento financeiro', 'verbose_name_plural': 'lançamentos financeiros'},
        ),
        migrations.AlterModelOptions(
            name='paymentcard',
            options={'verbose_name': 'cartão demonstrativo', 'verbose_name_plural': 'cartões demonstrativos'},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['-created_at'], 'verbose_name': 'transferência Pix', 'verbose_name_plural': 'transferências Pix'},
        ),
    ]
